Repository Altinn/altinn-correspondence, pull requests merged in 2024-11, with the labels that each got.

#417 Fix: Create reusable deploy-to-environment action, and reuse image published during deployment
  .github/actions/deploy-to-environment/action.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/deploy-to-environment.yml
Labels: ignore-for-release, kind/chore

#423 Fix CICD failing because it cannot find the deploy-to-environment action
  .github/workflows/ci-cd.yaml
Labels: kind/bug, ignore-for-release, kind/chore

#425 Fix deploy permission
  .github/actions/deploy-to-environment/action.yml
  .github/actions/update-infrastructure/action.yml
Labels: kind/bug

#427 Fix: Ensure correspondence is fetched before updating to Read or Confirmed
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  Test/Altinn.Correspondence.Tests/NotificationTests.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
Labels: kind/bug

#430 Legacy/overview auth!
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.API/Mappers/LegacyCorrespondenceOverviewMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceItemExt.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceOverviewExt.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewResponse.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Idporten/IdPortenXacmlMapper.cs
Labels: kind/feature-request, ignore-for-release

#436 Missing reference to Github environment in CI/CD
  .github/actions/deploy-to-environment/action.yml
  .github/workflows/ci-cd.yaml
Labels: kind/bug

#435 Changes to legacy response models
  src/Altinn.Correspondence.API/Mappers/LegacyCorrespondenceOverviewMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceOverviewExt.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewResponse.cs
Labels: kind/feature-request, ignore-for-release

#442 Adds confirm to response of legacy overview
  src/Altinn.Correspondence.API/Mappers/LegacyCorrespondenceOverviewMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceOverviewExt.cs
Labels: kind/bug, ignore-for-release

#421 Add logic for downloading attachment for A2 GUI
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/LegacyDownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/Helpers/UserClaimsHelper.cs
Labels: kind/feature

#444 fix: use correct lookupParty function, change onbehalfofpartyId to int
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryRequest.cs
Labels: kind/bug, ignore-for-release

#445 removepartId and disable auth
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewRequest.cs
Labels: ignore-for-release, kind/chore

#454 convert markdown to html for Legacy API
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/Helpers/TextValidation.cs
Labels: kind/feature-request, ignore-for-release

#457 remove isRecipient check in Legacy because user can have delegated permissions
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/LegacyDownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/LegacyUpdateCorrespondenceStatusHandler.cs
Labels: kind/bug, ignore-for-release

#462 Allow correspondence without attachment in form-data endpoint
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondencesMapper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesRequest.cs
Labels: kind/user-story

#460 correct auth for legacy overview
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnTokenXacmlMapper..cs
Labels: kind/feature-request, ignore-for-release

#459 Return Ext models in API instead of application models, rename models to avoid confusion
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondencesMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondenceResponse.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/enhancement, kind/breaking-change

#466 Remove internal endpoints in Swagger doc
  src/Altinn.Correspondence.API/Auth/IdportenCallbackInSwaggerFilter.cs
  src/Altinn.Correspondence.API/Controllers/HealthController.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.API/Controllers/MalwareScanController.cs
  src/Altinn.Correspondence.API/Controllers/MigrationController.cs
  src/Altinn.Correspondence.API/Program.cs
Labels: kind/chore

#468 add auth to all legacy enpoints
  src/Altinn.Correspondence.API/Mappers/LegacyGetCorrespondencesMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyGetCorrespondencesRequestExt.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesRequest.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/LegacyUpdateCorrespondenceStatusHandler.cs
Labels: kind/feature-request, ignore-for-release

#469 New (old) version number
  version.txt
Labels: kind/chore

#470 remove accessmanager for overview
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
Labels: ignore-for-release, kind/chore

#474 Add `markasread` functionality to LegacyController
  Test/Altinn.Correspondence.Tests/LegacyControllerTests.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/LegacyUpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
Labels: kind/feature, ignore-for-release

#475 Fjernet ubrukte felt fra collection
  altinn-correspondence-postman-collection.json
Labels: kind/bug

#480 LegacyController: PurgeCorrespondence
  Test/Altinn.Correspondence.Tests/LegacyControllerTests.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
Labels: kind/feature, ignore-for-release

#482 Lagt inn sperre for deploy når test app feiler
  .github/workflows/ci-cd.yaml
Labels: kind/bug

#483 Legacy: minor fixes in GetHistory & UpdateStatus
  Test/Altinn.Correspondence.Tests/LegacyControllerTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryResponse.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/LegacyUpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
Labels: kind/bug, ignore-for-release

#485 fix legacy tests
  Test/Altinn.Correspondence.Tests/LegacyControllerTests.cs
Labels: kind/bug, ignore-for-release

#488 Restore level auth of Dialogtoken
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
Labels: kind/bug

#495 Start all json property in lowercase
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceAttachmentExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceReplyOptionExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
  src/Altinn.Correspondence.API/Models/NotificationDetailsSummary.cs
  src/Altinn.Correspondence.API/Models/NotificationRecipientExt.cs
  src/Altinn.Correspondence.API/Models/PaginationMetaDataExt.cs
Labels: kind/bug, kind/breaking-change

#497 Changes to legacy list operation
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/Helpers/UserClaimsHelper.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnTokenXacmlMapper..cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/bug, ignore-for-release

#498 Legacy: fix authorize for write
  src/Altinn.Correspondence.API/Mappers/LegacyCorrespondenceOverviewMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceOverviewExt.cs
Labels: kind/bug, ignore-for-release

#509 Use highest status instead of newest for legacy
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
Labels: kind/feature-request, ignore-for-release

#503 Correct serviceOwner for legacy
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
Labels: kind/bug, ignore-for-release

#512 fix test in ci/cd
  .github/workflows/ci-cd.yaml
Labels: kind/bug

#513 Re-organize tests
  Test/Altinn.Correspondence.Tests/AttachmentControllerTests.cs
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  Test/Altinn.Correspondence.Tests/LegacyControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentDownloadTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentRetrievalTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentUploadTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/Base/AttachmentTestBase.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/Base/CorrespondenceTestBase.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceAttachmentTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceRetrievalTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceStatusTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/Base/LegacyTestBase.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyRetrievalTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacySearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyStatusTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/MalwareScanResultControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/NotificationTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/CancelNotificationHandlerTests.cs
Labels: kind/chore

#511 Feat: Support delegated permissions
  Test/Altinn.Correspondence.Tests/Helpers/MaskinportenWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/Helpers/UnitWebApplicationFactory.cs
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.Application/Altinn.Correspondence.Application.csproj
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentRequest.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesRequest.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsRequest.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewRequest.cs
  src/Altinn.Correspondence.Application/Helpers/UserClaimsHelper.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceRequest.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusRequest.cs
  src/Altinn.Correspondence.Common/Altinn.Correspondence.Common.csproj
  src/Altinn.Correspondence.Common/Helpers/StringExtensions.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnTokenXacmlMapper..cs
  src/Altinn.Correspondence.Integrations/Idporten/IdPortenXacmlMapper.cs
  src/Altinn.Correspondence.Persistence/Altinn.Correspondence.Persistence.csproj
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
Labels: kind/feature, kind/breaking-change

#525 Use highest status instead of latest status in logic
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/LegacyDownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeAttachment/PurgeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
Labels: kind/bug

#518 Systemuser authorization
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/Helpers/MaskinportenWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/Helpers/UnitWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceRetrievalTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/NotificationTests.cs
  src/Altinn.Correspondence.Application/DownloadAttachment/DownloadAttachmentHandler.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetAttachmentDetails/GetAttachmentDetailsHandler.cs
  src/Altinn.Correspondence.Application/GetAttachmentOverview/GetAttachmentOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
  src/Altinn.Correspondence.Application/PurgeAttachment/PurgeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UploadAttachment/UploadAttachmentHandler.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationOrderRequest.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnTokenXacmlMapper..cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogTokenXacmlMapper.cs
  src/Altinn.Correspondence.Integrations/Idporten/IdPortenXacmlMapper.cs
Labels: kind/feature

#526 Added markdown line break to messageBody
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
Labels: kind/bug

#523 PurgedCorrespondences should be available to recipient
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceStatusTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/Base/LegacyTestBase.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacySearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyStatusTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterDevService.cs
Labels: kind/feature-request

#534 Added condition for token type
  src/Altinn.Correspondence.API/Auth/CascadeAuthenticationHandler.cs
Labels: kind/bug
