Repository Altinn/altinn-correspondence, pull requests merged in 2024-12, with the labels that each got.

#536 Legacy now support other envs
  .azure/applications/api/main.bicep
  .azure/applications/api/params.bicepparam
  .azure/modules/containerApp/main.bicep
  .github/actions/deploy-to-environment/action.yml
  .github/actions/release-version/action.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/deploy-to-environment.yml
  .github/workflows/publish-branch.yml
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Common/Constants/AuthorizationConstants.cs
  src/Altinn.Correspondence.Core/Options/AltinnOptions.cs
Labels: kind/feature, ignore-for-release

#533 Feat: use URN prefix for organization number and social security number
  Test/Altinn.Correspondence.Tests/Factories/AttachmentBuilder.cs
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceAttachmentTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/InitializeAttachmentExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesExt.cs
  src/Altinn.Correspondence.API/ValidationAttributes/MD5ChecksumAttribute.cs
  src/Altinn.Correspondence.API/ValidationAttributes/OrganizationNumberAttribute.cs
  src/Altinn.Correspondence.API/ValidationAttributes/RequiredEnumAttribute.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/Helpers/UserClaimsHelper.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
  src/Altinn.Correspondence.Common/Constants/UrnConstants.cs
  src/Altinn.Correspondence.Common/Helpers/StringExtensions.cs
  src/Altinn.Correspondence.Core/Altinn.Correspondence.Core.csproj
  src/Altinn.Correspondence.Core/Models/Entities/AttachmentEntity.cs
  src/Altinn.Correspondence.Core/Models/Entities/CorrespondenceEntity.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnTokenXacmlMapper..cs
  src/Altinn.Correspondence.Integrations/Altinn/Events/AltinnEventBus.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogTokenXacmlMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogportenCorrespondenceMapper.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/feature, kind/breaking-change

#541 Chore: Group errors into categories
  src/Altinn.Correspondence.Application/DownloadAttachment/DownloadAttachmentHandler.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/LegacyDownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetAttachmentDetails/GetAttachmentDetailsHandler.cs
  src/Altinn.Correspondence.Application/GetAttachmentOverview/GetAttachmentOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/Helpers/UploadHelper.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateInitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeAttachment/PurgeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/LegacyUpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
  src/Altinn.Correspondence.Application/UploadAttachment/UploadAttachmentHandler.cs
Labels: kind/chore

#540 Fix: spell checks in model names
  Test/Altinn.Correspondence.LoadTests/test_initialize_and_upload_correspondence.js
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/Mappers/AttachmentStatusMapper.cs
  src/Altinn.Correspondence.API/Models/AtachmentStatusEvent.cs
  src/Altinn.Correspondence.API/Models/AttachmentDetailsExt.cs
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceDetailsExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceMigrationStatusExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceReplyOptionExt.cs
  src/Altinn.Correspondence.API/Models/Enums/InitializeAttachmentDataLocationTypeExt.cs
  src/Altinn.Correspondence.API/Models/InitializeAttachmentExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceAttachmentExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
  src/Altinn.Correspondence.API/Models/LegacyGetCorrespondencesRequestExt.cs
  src/Altinn.Correspondence.API/Models/MigrateCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/NotificationDetailsExt.cs
  src/Altinn.Correspondence.API/Models/NotificationExt.cs
  src/Altinn.Correspondence.API/Models/NotificationProcessStatusExt.cs
  src/Altinn.Correspondence.API/Models/NotificationRecipientExt.cs
  src/Altinn.Correspondence.API/Models/NotificationStatusExt.cs
Labels: kind/bug, kind/breaking-change

#543 Fix: Add Initialized status to correspondence always
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
Labels: kind/bug

#544 Fix: Determine caller role in purge correspondence
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Common/Helpers/ClaimsPrincipalExtensions.cs
Labels: kind/bug

#546 Feat: Add file name validation for attachments
  Test/Altinn.Correspondence.Tests/Factories/AttachmentBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/AttachmentHelper.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
  src/Altinn.Correspondence.Application/UploadAttachment/UploadAttachmentHandler.cs
Labels: kind/feature

#549 Repository tests
  Test/Altinn.Correspondence.Tests/Altinn.Correspondence.Tests.csproj
  Test/Altinn.Correspondence.Tests/Fixtures/PostgresTestcontainerFixture.cs
  Test/Altinn.Correspondence.Tests/Fixtures/TestApplicationDbContext.cs
  Test/Altinn.Correspondence.Tests/TestingRepository/CorrespondenceRepositoryTests.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
Labels: kind/enhancement

#550 Feat: Add support for custom recipients of a notifcation for a correspondence
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondenceNotificationMapper.cs
  src/Altinn.Correspondence.API/Mappers/NotificationMapper.cs
  src/Altinn.Correspondence.API/Models/CustomNotificationRecipientExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
  src/Altinn.Correspondence.Application/Altinn.Correspondence.Application.csproj
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/Helpers/MobilNumberHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondenceResponse.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/NotificationRequest.cs
  src/Altinn.Correspondence.Core/Models/Notifications/CustomNotificationRecipient.cs
  src/Altinn.Correspondence.Core/Models/Notifications/RecipientLookupResult.cs
Labels: kind/feature

#551 Consistent use of prefixes
  src/Altinn.Correspondence.API/appsettings.json
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnTokenXacmlMapper..cs
Labels: kind/bug

#553 Update docstrings and move classes into separate model files
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
  src/Altinn.Correspondence.API/Models/InitializedCorrespondencesExt.cs
  src/Altinn.Correspondence.API/Models/InitializedCorrespondencesNotificationsExt.cs
Labels: kind/documentation, ignore-for-release, kind/chore

#552 rename confirmed -> confirmationDate for legacy
  src/Altinn.Correspondence.API/Mappers/LegacyCorrespondenceOverviewMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceOverviewExt.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
Labels: kind/bug, ignore-for-release

#555 Fix deployments to at23 to be automatic
  .azure/applications/api/main.bicep
  .azure/applications/api/params.bicepparam
  .azure/modules/containerApp/main.bicep
  .github/actions/deploy-to-environment/action.yml
  .github/actions/release-version/action.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/deploy-to-environment.yml
  .github/workflows/publish-branch.yml
Labels: ignore-for-release, kind/chore

#561 Fix/correct maskinporten env
  .azure/modules/containerApp/main.bicep
  .github/workflows/deploy-to-environment.yml
Labels: kind/bug, ignore-for-release

#563 add missing non nullable data
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#560 add redis to bicep and auth
  .azure/infrastructure/main.bicep
  .azure/modules/containerApp/main.bicep
  .azure/modules/redis/main.bicep
  docker-compose.yml
  src/Altinn.Correspondence.API/Altinn.Correspondence.API.csproj
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.Core/Options/GeneralSettings.cs
Labels: kind/enhancement
