Repository Altinn/altinn-correspondence, pull requests merged in 2024-10, with the labels that each got.

#352 Add enhancement as label for release notes
  .github/release.yml
Labels: ignore-for-release, kind/chore

#347 Retrieve notifications from correspondenceRepository in hangfire job
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  src/Altinn.Correspondence.Application/CancelNotification/CancelNotificationHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
Labels: kind/enhancement

#342 Reduce RequestSendTime from 7 days to 1 hour for Notification Reminder when testing
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/feature

#353 Fix DialogToken authentication
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogTokenXacmlMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogportenXacmlMapper.cs
Labels: kind/bug

#346 Feat/correspondencelegacy getcorrespondences
  .azure/infrastructure/main.bicep
  .azure/infrastructure/params.bicepparam
  .azure/modules/containerApp/main.bicep
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.API/Mappers/LegacyGetCorrespondencesMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceContentExt.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceItemExt.cs
  src/Altinn.Correspondence.API/Models/LegacyGetCorrespondencesRequestExt.cs
  src/Altinn.Correspondence.Application/Configuration/AuthorizationConstants.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesRequest.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
  src/Altinn.Correspondence.Core/Models/Entities/SimpleParty.cs
  src/Altinn.Correspondence.Core/Models/Enums/SimplePartyType.cs
  src/Altinn.Correspondence.Core/Options/AltinnOptions.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAccessManangementService.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Core/Services/IAltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/Altinn/AcessManagement/AltinnAccessManagementService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: ignore-for-release

#358 fix wrong variable name
  .azure/infrastructure/main.bicep
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
Labels: ignore-for-release

#359 Wrong parameter used for publishing event.
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
Labels: kind/bug

#360 Feature/requested send time fortid
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/bug

#355 Include more details in InitializeCorrespondence response
  Test/Altinn.Correspondence.Tests/AttachmentControllerTests.cs
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  Test/Altinn.Correspondence.Tests/DialogportenTests.cs
  Test/Altinn.Correspondence.Tests/NotificationTests.cs
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondenceResponse.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnNotificationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Notifications/AltinnDevNotificationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Notifications/AltinnNotificationService.cs
Labels: kind/feature, kind/breaking-change

#367 Change legacy to use altinn token instead of maskinporten token
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
Labels: ignore-for-release

#370 Rettet feil i MalwareScan
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
Labels: kind/bug

#368 Use appsettings.local.json for local development
  .gitignore
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  src/Altinn.Correspondence.API/Program.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/Helpers/UploadHelper.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
  src/Altinn.Correspondence.Application/UploadAttachment/UploadAttachmentHandler.cs
  src/Altinn.Correspondence.Core/Options/AltinnOptions.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
Labels: kind/enhancement

#372 application/json response for InitializeCorrespondence, as well as response attributes added to api
  Test/Altinn.Correspondence.Tests/AttachmentControllerTests.cs
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/Helpers/AttachmentHelper.cs
  Test/Altinn.Correspondence.Tests/MalwareScanResultControllerTests.cs
  Test/Altinn.Correspondence.Tests/MigrationControllerTests.cs
  altinn-correspondence-v1.json
  src/Altinn.Correspondence.API/Controllers/AttachmentController.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Models/AttachmentOverviewExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceDetailsExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceOverviewExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
Labels: kind/feature

#375 add rules and labels for renovate bot
  renovate.json
Labels: kind/feature, ignore-for-release, kind/chore

#379 fix: use matchFileName and not fileMatch
  renovate.json
Labels: kind/chore

#382 add published to legacy get list
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
Labels: kind/feature-request, ignore-for-release

#385 Feature: Expand get legacy correspondence response model
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Core/Models/Entities/Party.cs
  src/Altinn.Correspondence.Core/Models/Entities/SimpleParty.cs
  src/Altinn.Correspondence.Core/Models/Enums/PartyType.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAccessManangementService.cs
  src/Altinn.Correspondence.Core/Services/IAltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
Labels: kind/feature-request, ignore-for-release

#384 add workflow for checking label for new PRs
  .github/workflows/check-label-for-pr.yml
Labels: ignore-for-release, kind/chore

#386 Fix Maskinporten token error
  src/Altinn.Correspondence.API/Auth/AltinnTokenEventsHelper.cs
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.API/Auth/JwtBearerEventsHelper.cs
  src/Altinn.Correspondence.API/Auth/MaskinportenSecurityTokenException.cs
Labels: kind/bug

#388 Legacy - authorize multiple recipients
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
Labels: kind/feature, ignore-for-release

#401 fix: Validate Content is not null in InitializeCorrespondence
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
Labels: kind/bug

#402 fix correct userparty
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
Labels: kind/bug, ignore-for-release

#403 Feat: Validation for language codes used
  Test/Altinn.Correspondence.Tests/CorrespondenceControllerTests.cs
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Persistence/Migrations/20241025123814_Update_Notication_Template_LanguageCode.Designer.cs
  src/Altinn.Correspondence.Persistence/Migrations/20241025123814_Update_Notication_Template_LanguageCode.cs
Labels: kind/feature

#409 Add message sender to Legacy list request
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
Labels: kind/feature-request, ignore-for-release

#411 Initial functionality for legacy correspondenceOverview
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewRequest.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
Labels: kind/feature-request, ignore-for-release

#413 Feat: LegacyController - Add LegacyGetCorrespondenceHistory
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryRequest.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryResponse.cs
Labels: kind/feature

#412 Added exception handler with slack notification
  .azure/infrastructure/main.bicep
  .azure/infrastructure/params.bicepparam
  .azure/modules/containerAppEnvironment/main.bicep
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
  src/Altinn.Correspondence.API/Helpers/SecurityHeadersMiddleware.cs
  src/Altinn.Correspondence.API/Helpers/SlackExceptionNotification.cs
  src/Altinn.Correspondence.API/Program.cs
Labels: kind/feature

#415 Add Recipient to user in GetCorrespondenceHistory
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryResponse.cs
Labels: kind/feature
