Repository Altinn/altinn-correspondence, pull requests merged in 2025-08, with the labels that each got.

#1180 Increase max file size to 2GB
  src/Altinn.Correspondence.API/Controllers/AttachmentController.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.Application/ApplicationConstants.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/AttachmentHelper.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateAttachmentHelper.cs
  src/Altinn.Correspondence.Application/MigrateToStorageProvider/MigrateToStorageProviderHandler.cs
  src/Altinn.Correspondence.Application/UploadAttachment/UploadAttachmentHandler.cs
  src/Altinn.Correspondence.Core/Repositories/IStorageRepository.cs
  src/Altinn.Correspondence.Persistence/Repositories/StorageRepository.cs
Labels: kind/feature

#1191 removed staging from tests env
  .github/workflows/test-performance.yml
Labels: kind/chore

#1182 1181 fixed long title of correspondence
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceEntityBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingUtility/CreateDialogRequestMapperTests.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#1210 1207 fixed the pipeline by copying bundle.exe to Container before running
  .azure/applications/migration/main.bicep
  .gitignore
Labels: kind/bug

#1212 Delete orphaned dialogs for purged correspondences
  Test/Altinn.Correspondence.Tests/TestingHandler/CleanupOrphanedDialogsHandlerTests.cs
  Test/Altinn.Correspondence.Tests/TestingRepository/CorrespondenceRepositoryTests.cs
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.API/Controllers/MaintenanceController.cs
  src/Altinn.Correspondence.Application/CleanupOrphanedDialogs/CleanupOrphanedDialogsHandler.cs
  src/Altinn.Correspondence.Application/CleanupOrphanedDialogs/CleanupOrphanedDialogsResponse.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/IHandler.cs
  src/Altinn.Correspondence.Common/Constants/AuthorizationConstants.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Core/Services/IDialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/user-story

#1224 Removed unnecessary reference to SA
  .azure/infrastructure/main.bicep
Labels: kind/chore

#1233 Made message summary field optional in request
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondencesMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceContentExt.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
Labels: kind/enhancement

#1238 Improved batching of migration jobs
  Test/Altinn.Correspondence.Tests/TestingHandler/MigrateCorrespondenceHandlerTests.cs
  src/Altinn.Correspondence.API/Program.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MakeCorrespondenceAvailableRequest.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Integrations/Altinn/Notifications/AltinnNotificationService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/enhancement

#1239 Validate max total attachments
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceContentExt.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/bug

#1242 Fix/limit searchtag to 63 chars
  Test/Altinn.Correspondence.Tests/Dialogporten/DialogportenServiceTests.cs
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceEntityBuilder.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#1252 Created batch correspondences should have their own ReplyOptions
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceExt.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
Labels: kind/bug

#1261 Optimize cleanup dialog batching for prod
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceEntityBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/CleanupOrphanedDialogsHandlerTests.cs
  Test/Altinn.Correspondence.Tests/TestingRepository/CorrespondenceRepositoryTests.cs
  src/Altinn.Correspondence.API/Controllers/MaintenanceController.cs
  src/Altinn.Correspondence.Application/CleanupOrphanedDialogs/CleanupOrphanedDialogsHandler.cs
  src/Altinn.Correspondence.Application/CleanupOrphanedDialogs/CleanupOrphanedDialogsRequest.cs
  src/Altinn.Correspondence.Application/IHandler.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/enhancement
