Repository Altinn/altinn-correspondence, pull requests merged in 2025-02, with the labels that each got.

#662 Updated GetCorrespondenceContent endpoint to produce text/plain
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
Labels: kind/bug

#664 Limit allowed filetypes
  Test/Altinn.Correspondence.Tests/Altinn.Correspondence.Tests.csproj
  Test/Altinn.Correspondence.Tests/Data/Markdown.txt
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceAttachmentTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.Application/ApplicationConstants.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/AttachmentHelper.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
Labels: kind/enhancement

#674 Added validation to prevent empty recipients lists for custom recipients
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
Labels: kind/enhancement

#676 Return notification history in A2 format
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationStatusDetailsResponse.cs
  src/Altinn.Correspondence.Integrations/Altinn/Notifications/AltinnNotificationService.cs
Labels: kind/bug

#681 remove duplicate attachmentIds
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/enhancement

#680 Enhancement/improve accept header validation
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/AcceptHeaderValidationTests.cs
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/Helpers/AcceptHeaderValidationMiddleware.cs
  src/Altinn.Correspondence.API/Program.cs
Labels: kind/enhancement

#686 Improved Accept Header Validation Middleware
  Test/Altinn.Correspondence.Tests/TestingFeature/AcceptHeaderValidationTests.cs
  src/Altinn.Correspondence.API/Helpers/AcceptHeaderValidationMiddleware.cs
Labels: kind/enhancement

#689 Made Accept header in requests optional
  Test/Altinn.Correspondence.Tests/TestingFeature/AcceptHeaderValidationTests.cs
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Helpers/AcceptHeaderValidationMiddleware.cs
Labels: kind/bug, kind/enhancement

#690 chore(performance): implement changes
  Test/Altinn.Correspondence.LoadTests/correspondence/create-and-upload-correspondence-single-user.js
  Test/Altinn.Correspondence.LoadTests/correspondence/create-and-upload-correspondence.js
  Test/Altinn.Correspondence.LoadTests/correspondence/create-correspondence.js
  Test/Altinn.Correspondence.LoadTests/correspondence/get-correspondence-overview.js
  Test/Altinn.Correspondence.LoadTests/correspondence/get-correspondence.js
Labels: kind/chore

#682 delete dialog when publish goes wrong
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Core/Services/IDialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
Labels: kind/feature

#706 Update dependencies
  .azure/applications/api/main.bicep
  .azure/infrastructure/main.bicep
  .azure/modules/keyvault/addReaderRoles.bicep
  .azure/modules/keyvault/create.bicep
  .azure/modules/keyvault/upsertSecret.bicep
  .azure/modules/postgreSql/AddAdministrationAccess.bicep
  .azure/modules/postgreSql/create.bicep
  .azure/modules/storageAccount/create.bicep
  Test/Altinn.Correspondence.LoadTests.DatabasePopulater/Altinn.Correspondence.LoadTests.DatabasePopulater.csproj
  Test/Altinn.Correspondence.Tests/Altinn.Correspondence.Tests.csproj
  renovate.json
  src/Altinn.Correspondence.API/Altinn.Correspondence.API.csproj
  src/Altinn.Correspondence.Application/Altinn.Correspondence.Application.csproj
  src/Altinn.Correspondence.Common/Altinn.Correspondence.Common.csproj
  src/Altinn.Correspondence.Core/Altinn.Correspondence.Core.csproj
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Persistence/Altinn.Correspondence.Persistence.csproj
  version.txt
Labels: kind/chore

#707 Deploy to at22 after test because they cannot be deployed concurrently
  .github/workflows/ci-cd.yaml
Labels: kind/chore

#722 Background jobs must be scheduled using service from its own service scope
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
Labels: kind/bug

#736 Validate the resource type. Essential because it will fail in Dialogp…
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/ResourceRightsServiceTests.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Core/Repositories/IResourceRightsService.cs
  src/Altinn.Correspondence.Core/Services/IResourceRegistryService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/ResourceRegistry/ResourceRegistryService.cs
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
  version.txt
Labels: kind/bug

#723 Make eventBus publishing into a backgroundjob
  Test/Altinn.Correspondence.LoadTests.DatabasePopulater/dagl-correspondence-1.xml
  src/Altinn.Correspondence.Application/CorrespondenceDueDate/CorrespondenceDueDateHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeAttachment/PurgeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/LegacyUpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
Labels: kind/enhancement

#738 change cachetime
  src/Altinn.Correspondence.Integrations/Altinn/ResourceRegistry/ResourceRegistryService.cs
Labels: kind/enhancement

#711 Return ProblemDetails on exception
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Program.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Integrations/Altinn/ContactReservationRegistry/ContactReservationRegistryService.cs
  src/Altinn.Correspondence.Integrations/Hangfire/DependencyInjection.cs
  src/Altinn.Correspondence.Integrations/Hangfire/SlackExceptionHandler.cs
  src/Altinn.Correspondence.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/chore

#760 Stop counting rows in search
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/chore

#762 add name to legacy attachment object
  src/Altinn.Correspondence.API/Mappers/CorrespondenceAttachmentMapper.cs
  src/Altinn.Correspondence.API/Mappers/LegacyCorrespondenceOverviewMapper.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceAttachmentExt.cs
  src/Altinn.Correspondence.API/Models/LegacyCorrespondenceOverviewExt.cs
Labels: kind/bug

#735 Update descriptions
  .github/workflows/check-label-for-pr.yml
  src/Altinn.Correspondence.API/Controllers/AttachmentController.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.API/Models/AtachmentStatusEvent.cs
  src/Altinn.Correspondence.API/Models/Enums/AttachmentStatus.cs
  src/Altinn.Correspondence.API/Models/Enums/CorrespondenceStatusExt.cs
  src/Altinn.Correspondence.API/Models/Enums/InitializedCorrespondecesStatusExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceAttachmentExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceContentExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
  src/Altinn.Correspondence.API/Models/InitializedCorrespondencesExt.cs
  src/Altinn.Correspondence.API/Models/InitializedCorrespondencesNotificationsExt.cs
  src/Altinn.Correspondence.API/Models/NotificationExt.cs
  src/Altinn.Correspondence.API/Models/NotificationProcessStatusExt.cs
  src/Altinn.Correspondence.API/Models/NotificationStatusExt.cs
Labels: kind/documentation

#768 add missing file changes for displayname
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/Mappers/AttachmentDetailsMapper.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
Labels: kind/bug

#769 set sender as null if messageSender is not ovverriden
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug
