Repository Altinn/altinn-correspondence, pull requests merged in 2025-09, with the labels that each got.

#1267 Changed auth slack test
  Test/Altinn.Correspondence.Tests/TestingFeature/SlackTest.cs
  src/Altinn.Correspondence.API/Controllers/SlackTestController.cs
Labels: kind/bug

#1274 Use IdempotencyKey for activities when creating dialog for migrated correspondence
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#1294 Update validation to match Dialogporten
  Test/Altinn.Correspondence.Tests/Altinn.Correspondence.Tests.csproj
  Test/Altinn.Correspondence.Tests/Data/Markdown1.txt
  Test/Altinn.Correspondence.Tests/Data/Markdown2.txt
  Test/Altinn.Correspondence.Tests/Data/Markdown3.txt
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  docker-compose.yml
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceContentExt.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/enhancement

#1324 Enabled live sync A2-A3-DP on a secondary queue
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/Invariants/HangfireStorageCompatibilityTests.cs
  Test/Altinn.Correspondence.Tests/TestingRepository/CorrespondenceRepositoryTests.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
  src/Altinn.Correspondence.Integrations/Hangfire/DependencyInjection.cs
  src/Altinn.Correspondence.Integrations/Hangfire/HangfireQueues.cs
Labels: kind/feature

#1337 1322 added condition endpoint while sending Notification Order V2 to Core
  Test/Altinn.Correspondence.Tests/TestingHandler/CreateNotificationHandlerTests.cs
  src/Altinn.Correspondence.Application/CheckNotification/CheckNotificationHandler.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationHandler.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationOrderRequestV2.cs
Labels: kind/feature

#1338 1325 added OverrideRegisteredContactInformation flag that decides if we send to default contact info. of corerspondence or only custom recipients for notification
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondenceNotificationMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationHandler.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/NotificationRequest.cs
Labels: kind/feature

#1321 La til syncing i MarkCorrespondenceAsReadHandler
  src/Altinn.Correspondence.Application/MarkCorrespondenceAsRead/MarkCorrespondenceAsReadHandler.cs
Labels: kind/feature

#1354 High availability for production database
  .azure/infrastructure/main.bicep
  .azure/modules/postgreSql/create.bicep
Labels: kind/feature

#1348 Clean-up dialogs set with expiresAt ⚠️
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceEntityBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/CleanupPerishingDialogsHandlerTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/RestoreSoftDeletedDialogsHandlerTests.cs
  src/Altinn.Correspondence.API/Controllers/MaintenanceController.cs
  src/Altinn.Correspondence.Application/CleanupPerishingDialogs/CleanupPerishingDialogsHandler.cs
  src/Altinn.Correspondence.Application/CleanupPerishingDialogs/CleanupPerishingDialogsRequest.cs
  src/Altinn.Correspondence.Application/CleanupPerishingDialogs/CleanupPerishingDialogsResponse.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/RestoreSoftDeletedDialogs/RestoreSoftDeletedDialogsHandler.cs
  src/Altinn.Correspondence.Application/RestoreSoftDeletedDialogs/RestoreSoftDeletedDialogsRequest.cs
  src/Altinn.Correspondence.Application/RestoreSoftDeletedDialogs/RestoreSoftDeletedDialogsResponse.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Core/Services/IDialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Factories/PatchDialogRequestBuilder.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/bug

#1361 Improved legacy search
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacySearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingRepository/CorrespondenceRepositoryTests.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/Helpers/UserClaimsHelper.cs
  src/Altinn.Correspondence.Common/Constants/UrnConstants.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAccessManangementService.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/chore

#1363 Create a dialog transmission for related correspondences
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.API/Models/Enums/ReferenceTypeExt.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/HangfireScheduleHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Core/Models/Enums/ReferenceType.cs
  src/Altinn.Correspondence.Core/Services/IDialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogTransmissionMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Models/CreateTransmissionRequest.cs
Labels: kind/feature

#1373 1360 change authentication fix pipeline
  .github/workflows/ci-cd.yaml
  README_STATISTICS.md
  src/Altinn.Correspondence.API/appsettings.Development.json
  src/Altinn.Correspondence.API/appsettings.json
Labels: kind/bug

#1371 Prevent Correspondences and certain sync events with Self-Identified Users to update Dialogporten
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/SyncCorrespondenceForwardingEventTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/MigrateCorrespondenceHandlerTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/SyncCorrespondenceStatusEventHandlerTests.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/SyncCorrespondenceEvent/SyncCorrespondenceStatusEventHandler.cs
  src/Altinn.Correspondence.Common/Constants/UrnConstants.cs
  src/Altinn.Correspondence.Common/Helpers/StringExtensions.cs
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/bug

#1362 ⚠️ Add permission roles for switch to RBAC permission model
  .azure/applications/api/main.bicep
  .azure/applications/migration/main.bicep
  .azure/infrastructure/main.bicep
  .azure/modules/keyvault/addReaderRoles.bicep
  .azure/modules/keyvault/addSecretsOfficerRole.bicep
Labels: kind/user-story

#1382 fix incorrect contentReference for messageBody
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogTransmissionMapper.cs
Labels: kind/bug
