Repository Altinn/altinn-correspondence, pull requests merged in 2025-10, with the labels that each got.

#1398 Prevent Dialog with UpdatedAt in the future
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceEntityBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingUtility/CreateDialogRequestMapperTests.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#1399 1341 added correct text for reminder, added tests
  Test/Altinn.Correspondence.Tests/TestingUtility/CreateDialogRequestMapperTests.cs
  src/Altinn.Correspondence.Application/CheckNotificationDelivery/CheckNotificationDeliveryHandler.cs
  src/Altinn.Correspondence.Core/Services/Enums/DialogportenTextType.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogportenText.cs
Labels: kind/bug

#1396 1114 mulighet for overstyring av mottakers reservasjon i krr under bestilling av varsling
  Test/Altinn.Correspondence.Tests/TestingHandler/CreateNotificationHandlerTests.cs
  src/Altinn.Correspondence.API/Models/BaseCorrespondenceExt.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationHandler.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationOrderRequestV2.cs
Labels: kind/feature

#1405 Create a transmission when publishing
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.Application/Helpers/HangfireScheduleHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/user-story, kind/enhancement

#1416 Skip slack notification for exceptions on the migration endpoints
  Test/Altinn.Correspondence.Tests/TestingIntegrations/Slack/SlackExceptionNotificationHandlerTests.cs
  src/Altinn.Correspondence.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/enhancement

#1420 IdempotencyKey is not supported for multiple recipients
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/bug

#1419 add propertyList value as search tag
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/user-story

#1422 Added Better handling of MessageTitle to improve Dialogporten integration
  Test/Altinn.Correspondence.Tests/Factories/MigrateCorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingUtility/CreateDialogRequestMapperTests.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogTransmissionMapper.cs
Labels: kind/bug, blocked

#1430 Fix/optimize get correspondence for sync
  Test/Altinn.Correspondence.Tests/TestingHandler/SyncCorrespondenceForwardingEventRequestTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/SyncCorrespondenceNotificationEventHandlerTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/SyncCorrespondenceStatusEventHandlerTests.cs
  src/Altinn.Correspondence.Application/SyncCorrespondenceEvent/SyncCorrespondenceForwardingEventHandler.cs
  src/Altinn.Correspondence.Application/SyncCorrespondenceEvent/SyncCorrespondenceNotificationEventHandler.cs
  src/Altinn.Correspondence.Application/SyncCorrespondenceEvent/SyncCorrespondenceStatusEventHandler.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/bug
