Repository Altinn/altinn-correspondence, pull requests merged in 2025-05, with the labels that each got.

#951 fixed problem with attachment ids to DP
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#963 Trim search tags
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#954 Part 3: Migrate files from old to new storage providers
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/MigrateToStorageProvider/MigrateToStorageProviderHandler.cs
  src/Altinn.Correspondence.Core/Repositories/IAttachmentRepository.cs
  src/Altinn.Correspondence.Core/Services/IResourceRegistryService.cs
  src/Altinn.Correspondence.Integrations/Azure/AzureResourceManagerService.cs
  src/Altinn.Correspondence.Integrations/Azure/SasTokenService.cs
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
  src/Altinn.Correspondence.Persistence/Repositories/AttachmentRepository.cs
  src/Altinn.Correspondence.Persistence/Repositories/StorageRepository.cs
Labels: kind/feature

#956 Prevent duplicate publish
  Test/Altinn.Correspondence.Tests/TestingIntegrations/RedLock/DistributedLockHelperTests.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
  src/Altinn.Correspondence.Integrations/Redlock/DistributedLockHelper.cs
Labels: kind/bug

#981 Set maximum 100 attachments
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceContentExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceContentExt.cs
Labels: kind/feature

#983 Need correct role assignment to enable malware scan
  .azure/modules/identity/create.bicep
Labels: kind/bug

#974 Cancel notifications when sent instead of when correspondence cancelled
  src/Altinn.Correspondence.Application/CancelNotification/CancelNotificationHandler.cs
  src/Altinn.Correspondence.Application/CheckNotification/CheckNotificationHandler.cs
Labels: kind/bug

#973 Re-factor to use org code
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/ResourceRightsServiceTests.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/Helpers/AttachmentHelper.cs
  src/Altinn.Correspondence.Application/MigrateToStorageProvider/MigrateToStorageProviderHandler.cs
  src/Altinn.Correspondence.Core/Services/IResourceRegistryService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/ResourceRegistry/ResourceRegistryService.cs
  src/Altinn.Correspondence.Integrations/Azure/AzureResourceManagerService.cs
Labels: kind/enhancement

#986 Updated AZ CLI version in ci/cd
  .github/actions/migrate-database/action.yml
  .github/actions/release-version/action.yml
  .github/tools/revisionVerifier.sh
Labels: kind/bug

#958 Cancel notification before deleting dialog
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/CancelNotificationHandlerTests.cs
  src/Altinn.Correspondence.Application/CancelNotification/CancelNotificationHandler.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
Labels: kind/bug

#992 Legacy download should use same tokens as normal for Dialogporten
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/LegacyDownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
Labels: kind/bug

#1000 If no idempotency key exists, create one
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
Labels: kind/bug

#994 Improve custom recipients initialize correspondence
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/CreateNotificationHandlerTests.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondenceNotificationMapper.cs
  src/Altinn.Correspondence.API/Mappers/NotificationMapper.cs
  src/Altinn.Correspondence.API/Models/CustomNotificationRecipientExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
  src/Altinn.Correspondence.API/Models/NotificationDetailsExt.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationHandler.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsHandler.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/NotificationRequest.cs
  src/Altinn.Correspondence.Core/Models/Notifications/CustomNotificationRecipient.cs
  src/Altinn.Correspondence.Core/Models/Notifications/EmailNotificationWithResult.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationOrderRequestResponseV2.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationOrderRequestV2.cs
  src/Altinn.Correspondence.Integrations/Altinn/Notifications/AltinnDevNotificationService.cs
  src/Altinn.Correspondence.Persistence/Migrations/20250507210753_CorrespondenceNotification_ShipmentId.cs
Labels: kind/feature

#997 Updated postman collection
  altinn-correspondence-postman-collection.json
Labels: kind/enhancement

#1004 updated unit tests to account for updates to correspondence ID and at…
  Test/Altinn.Correspondence.Tests/Factories/MigrateAttachmentBuilder.cs
  Test/Altinn.Correspondence.Tests/Factories/MigrateCorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
Labels: kind/bug

#1012 Removed validation om migrated message titles
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
Labels: kind/feature

#1010 Staging should have prodlike replica count
  .azure/modules/containerApp/main.bicep
Labels: kind/chore

#1013 added obsolete and got customNotificationRecipients back
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondenceNotificationMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
Labels: kind/bug

#1006 Updated hangfire exception to include system
  src/Altinn.Correspondence.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/chore

#1020 Give Legacy.GetOverview Access to IsMigrating correspondences
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationAccessTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/LegacyGetCorrespondenceOverviewHandler.cs
Labels: migration

#1024 Added logic to stop overview when correspondence is purged
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyDeletionTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
Labels: kind/bug

#1027 Changed renovate config
  renovate.json
Labels: kind/chore
