Repository Altinn/altinn-correspondence, pull requests merged in 2025-06, with the labels that each got.

#1041 Added sendersReference to search
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/GetCorrespondencesRequest.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/feature

#1042 Added contentType as HTML
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondenceNotificationMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationHandler.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/NotificationRequest.cs
  src/Altinn.Correspondence.Core/Models/Enums/EmailContentType.cs
  src/Altinn.Correspondence.Core/Models/Notifications/NotificationOrderRequestV2.cs
Labels: kind/feature

#1050 Update GetCorrespondenceDetails to show Notification History for Altinn 2 Correspondences
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceDetails/GetCorrespondenceDetailsHandler.cs
  src/Altinn.Correspondence.Application/Helpers/NotificationMapper.cs
Labels: kind/bug

#1056 Added altinn 2 notificationinfo to LegacyGetCorrespondenceHistory
  Test/Altinn.Correspondence.Tests/TestingController/Migration/Base/MigrationTestBase.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
Labels: kind/bug, kind/user-story

#1057 polly retries for network calls
  Test/Altinn.Correspondence.Tests/Common/HttpRetryPolicyTests.cs
  src/Altinn.Correspondence.API/Altinn.Correspondence.API.csproj
  src/Altinn.Correspondence.Application/Altinn.Correspondence.Application.csproj
  src/Altinn.Correspondence.Common/Altinn.Correspondence.Common.csproj
  src/Altinn.Correspondence.Common/Helpers/HttpClientBuilderExtensions.cs
  src/Altinn.Correspondence.Core/Altinn.Correspondence.Core.csproj
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
Labels: kind/feature

#1058 Set storage provider on attachment during migrate
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateAttachmentHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateAttachmentHelper.cs
Labels: kind/bug

#1063 Return errorCode in problemDetails
  src/Altinn.Correspondence.API/Controllers/AttachmentController.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.API/Controllers/LegacyCorrespondenceController.cs
  src/Altinn.Correspondence.API/Controllers/MalwareScanController.cs
  src/Altinn.Correspondence.API/Controllers/MigrationController.cs
Labels: kind/enhancement

#750 chore(performance): Create readmes for performance tests
  README.md
  Test/Altinn.Correspondence.LoadTests/correspondence/README.md
Labels: kind/documentation

#1073 Filter out OPTIONS calls from logs
  src/Altinn.Correspondence.API/Altinn.Correspondence.API.csproj
  src/Altinn.Correspondence.Integrations/Azure/OpenTelemetryConfiguration.cs
  tools/Altinn.Correspondence.Dashboard/Altinn.Correspondence.Dashboard.csproj
  tools/Altinn.Correspondence.Dashboard/Program.cs
Labels: kind/chore

#1089 Fix bug where adding to activity log was attempted for migrated elements
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
Labels: kind/bug

#1090 Show environment name in 'deploy to environment' workflow runs
  .github/workflows/deploy-to-environment.yml
Labels: kind/enhancement

#1088 Use parentorg roles for suborg when validating confidential correspondence
  Test/Altinn.Correspondence.Tests/Brreg/BrregDevServiceTests.cs
  Test/Altinn.Correspondence.Tests/Brreg/BrregServiceIntegrationTests.cs
  Test/Altinn.Correspondence.Tests/Brreg/BrregServiceTests.cs
  Test/Altinn.Correspondence.Tests/TestingHandler/PublishCorrespondenceHandlerTests.cs
  src/Altinn.Correspondence.Application/ApplicationConstants.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Core/Models/Brreg/SubOrganizationDetails.cs
  src/Altinn.Correspondence.Core/Services/IBrregService.cs
  src/Altinn.Correspondence.Integrations/Brreg/BrregDevService.cs
  src/Altinn.Correspondence.Integrations/Brreg/BrregService.cs
Labels: kind/feature

#1112 1109 fix json converter
  Test/Altinn.Correspondence.Tests/TestingUtility/NotificationStatusV2ConverterTests.cs
  src/Altinn.Correspondence.Core/Models/Enums/NotificationStatusV2.cs
Labels: kind/bug
