Repository Altinn/altinn-correspondence, pull requests merged in 2025-07, with the labels that each got.

#1131 Fix/log processor
  src/Altinn.Correspondence.Integrations/OpenTelemetry/RequestFilterProcessor.cs
Labels: kind/bug

#1130 UpdatedAt should be latest date
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Integrations/OpenTelemetry/RequestFilterProcessor.cs
Labels: kind/bug

#1134 1022-update-postman-tjenesteautentisering
  altinn-correspondence-postman-collection.json
Labels: kind/chore

#1151 added handling for empty message summary
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/bug

#1153 Change slack filter for hangfire retry
  src/Altinn.Correspondence.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/chore

#1148 1146 removed sender in initialize attachments, added deprecated to the API
  Test/Altinn.Correspondence.Tests/Factories/AttachmentBuilder.cs
  Test/Altinn.Correspondence.Tests/Factories/MigrateAttachmentBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationAccessTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Migration/MigrationControllerTests.cs
  src/Altinn.Correspondence.API/Mappers/InitializeAttachmentMapper.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondencesMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeAttachmentExt.cs
  src/Altinn.Correspondence.Application/InitializeAttachment/InitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Common/Constants/UrnConstants.cs
Labels: kind/feature

#1119 Simualted malware scan instead of auto publish for local dev and tests
  Test/Altinn.Correspondence.Tests/Helpers/AttachmentHelper.cs
  Test/Altinn.Correspondence.Tests/Helpers/CorrespondenceHelper.cs
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/Invariants/HangfireStorageCompatibilityTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentDownloadTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Attachment/AttachmentUploadTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceAttachmentTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceRetrievalTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceStatusTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyDeletionTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyRetrievalTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacySearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyStatusTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/MalwareScanResultControllerTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/NotificationTests.cs
  src/Altinn.Correspondence.Application/Helpers/AttachmentHelper.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterDevService.cs
Labels: kind/enhancement

#1159 Fix recipient with systemuser token
  Test/Altinn.Correspondence.Tests/TestingFeature/MaskinportenAuthenticationTests.cs
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
  src/Altinn.Correspondence.Common/Constants/UrnConstants.cs
Labels: kind/bug

#1162 first draft
  src/Altinn.Correspondence.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/chore

#1160 874 ikke feil release fordi vi ikke har bumpet versjon
  .github/workflows/ci-cd.yaml
Labels: kind/bug

#1106 No password access to database
  .azure/applications/migration/main.bicep
  .azure/infrastructure/main.bicep
  .azure/infrastructure/params.bicepparam
  .azure/modules/postgreSql/create.bicep
  .github/actions/deploy-to-environment/action.yml
  .github/actions/update-infrastructure/action.yml
  .github/tools/pwdGenerator.ps1
  README.md
Labels: kind/enhancement

#1163 Bump version
  Test/Altinn.Correspondence.Tests/TestingFeature/MaskinportenAuthenticationTests.cs
  version.txt
Labels: kind/chore

#1166 Added AttachmentsDownloaded as an active status in legacy search
  src/Altinn.Correspondence.Persistence/Helpers/QueryableExtensions.cs
Labels: kind/bug
