Repository Altinn/altinn-correspondence, pull requests merged in 2025-04, with the labels that each got.

#885 Fix/at environments
  .azure/applications/api/main.bicep
Labels: kind/bug

#897 Removed Dependencies to ResourceRegister from Migration Controller
  Test/Altinn.Correspondence.Tests/Helpers/ServiceCollectionExtensions.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondence/MigrateCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateInitializeAttachmentHandler.cs
  src/Altinn.Correspondence.Application/MigrateCorrespondenceAttachment/MigrateUploadAttachmentHandler.cs
  src/Altinn.Correspondence.Core/Repositories/IAltinnAuthorizationService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
Labels: product/meldingstjenesten, kind/enhancement

#903 Enable prepared transactions to improve performance
  .azure/modules/postgreSql/create.bicep
Labels: kind/chore

#890 Write JSON formatted logs to console
  src/Altinn.Correspondence.API/Helpers/PropertyPropagationEnricher.cs
  src/Altinn.Correspondence.API/Program.cs
Labels: kind/feature-request

#896 Fix timing issue
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/MalwareScanResultControllerTests.cs
  src/Altinn.Correspondence.Application/Helpers/HangfireScheduleHelper.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
Labels: kind/bug

#907 Let Dialogporten decide when a dialog has been created
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Models/CreateDialogRequest.cs
Labels: kind/bug

#909 Fixed issue where duplicate ReadyForPublish was generated locally
  .azure/infrastructure/main.bicep
  .azure/modules/redis/main.bicep
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/bug

#912 Add instance id property to log event in addition to log context so t…
  src/Altinn.Correspondence.API/Helpers/PropertyPropagationEnricher.cs
Labels: kind/enhancement

#899 Added AttachmentsDownloaded status and tests
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceAttachmentTests.cs
  src/Altinn.Correspondence.API/Models/Enums/CorrespondenceStatusExt.cs
  src/Altinn.Correspondence.Application/DownloadCorrespondenceAttachment/DownloadCorrespondenceAttachmentHandler.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Core/Models/Enums/CorrespondenceStatus.cs
Labels: kind/feature

#941 Add specific ID's to ensure attachment ordering is preserved.
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Models/CreateDialogRequest.cs
Labels: kind/enhancement

#939 Proper error message when contact reservation registry lookup fails
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/chore

#944 894 asynkron opprettelse av notifications
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationHandler.cs
  src/Altinn.Correspondence.Application/CreateNotification/CreateNotificationRequest.cs
  src/Altinn.Correspondence.Application/Helpers/HangfireScheduleHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
  src/Altinn.Correspondence.Core/Services/Enums/AltinnEventType.cs
Labels: kind/feature
