Repository Altinn/altinn-correspondence, pull requests merged in 2025-01, with the labels that each got.

#567 Add senderName to notifications
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: kind/feature

#569 Functionality for recipientName token in message
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Core/Services/IAltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
Labels: kind/feature

#574 Setup yt01, at21, at22, at23 and at24 as possible environments
  .github/workflows/ci-cd.yaml
  .github/workflows/deploy-to-environment.yml
Labels: kind/chore

#579 Cpu bicep parameter as json
  .azure/modules/containerApp/main.bicep
Labels: kind/bug

#583 Removed InitializeCorrespondences operation status
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Mappers/InitializeCorrespondencesMapper.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondencesResponseExt.cs
Labels: kind/chore

#598 Legacy api performance tuning
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/chore

#605 remove pagination from legacy search
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacySearchTests.cs
  Test/Altinn.Correspondence.Tests/TestingRepository/CorrespondenceRepositoryTests.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: ignore-for-release, kind/chore

#608 get name instead of orgNumber for service owner
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Integrations/Altinn/ResourceRegistry/ResourceRightsService.cs
Labels: ignore-for-release, kind/enhancement

#613 correct null check for auth level
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
Labels: kind/bug, ignore-for-release

#615 Feature/reply option requires https
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  src/Altinn.Correspondence.API/Models/CorrespondenceReplyOptionExt.cs
Labels: kind/enhancement, kind/breaking-change

#618 Added request level caching of auth results
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
Labels: kind/bug

#612 Cache API responses in AltinnRegisterService
  Test/Altinn.Correspondence.Tests/TestingUtility/CacheHelpersTests.cs
  src/Altinn.Correspondence.Common/Helpers/CacheHelpers.cs
  src/Altinn.Correspondence.Integrations/Altinn/AccessManagement/AltinnAccessManagementService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
Labels: kind/feature

#619 add validation for custom recipients with tags
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceNotificationTests.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
Labels: product/meldingstjenesten, kind/enhancement, kind/breaking-change

#616 Cache API responses in ResourceRightsService
  Test/Altinn.Correspondence.Tests/TestingFeature/ResourceRightsServiceTests.cs
  src/Altinn.Correspondence.Integrations/Altinn/ResourceRegistry/GetResourceResponse.cs
  src/Altinn.Correspondence.Integrations/Altinn/ResourceRegistry/ResourceRightsService.cs
Labels: kind/feature

#624 SblBridge through Storage
  .azure/modules/containerApp/main.bicep
  altinn-correspondence-postman-collection.json
  src/Altinn.Correspondence.API/appsettings.Development.json
  src/Altinn.Correspondence.Application/ProcessLegacyParty/ProcessLegacyPartyHandler.cs
  src/Altinn.Correspondence.Core/Services/IAltinnStorageService.cs
  src/Altinn.Correspondence.Integrations/Altinn/SblBridge/AltinnSblBridgeDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/SblBridge/AltinnSblBridgeService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Storage/AltinnStorageDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Storage/AltinnStorageService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Storage/SblBridgeParty.cs
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
Labels: kind/feature

#630 Update dependencies
  .github/actions/migrate-database/action.yml
  Test/Altinn.Correspondence.LoadTests.DatabasePopulater/Altinn.Correspondence.LoadTests.DatabasePopulater.csproj
  Test/Altinn.Correspondence.Tests/Altinn.Correspondence.Tests.csproj
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceSearchTests.cs
  src/Altinn.Correspondence.API/Altinn.Correspondence.API.csproj
  src/Altinn.Correspondence.Application/Altinn.Correspondence.Application.csproj
  src/Altinn.Correspondence.Common/Altinn.Correspondence.Common.csproj
  src/Altinn.Correspondence.Core/Altinn.Correspondence.Core.csproj
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Persistence/Altinn.Correspondence.Persistence.csproj
Labels: kind/chore

#636 add IsConfirmationNeeded to legacy
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyDeletionTests.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/GetCorespondences/LegacyGetCorrespondencesResponse.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
Labels: ignore-for-release, kind/enhancement

#638 Fix use of formatting tokens
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogportenText.cs
Labels: kind/bug

#639 Set max file size on attachment
  src/Altinn.Correspondence.Application/ApplicationConstants.cs
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/UploadAttachment/UploadAttachmentHandler.cs
Labels: kind/feature

#643 Resource whitelist
  .azure/infrastructure/main.bicep
  .azure/infrastructure/params.bicepparam
  .azure/modules/containerApp/main.bicep
  .github/actions/deploy-to-environment/action.yml
  .github/actions/update-infrastructure/action.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/deploy-to-environment.yml
  src/Altinn.Correspondence.API/appsettings.Development.json
  src/Altinn.Correspondence.Application/Errors.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Core/Options/GeneralSettings.cs
Labels: kind/feature

#652 Setup Correspondence with Serilog
  src/Altinn.Correspondence.API/Altinn.Correspondence.API.csproj
  src/Altinn.Correspondence.API/Program.cs
Labels: kind/feature
