Repository Altinn/altinn-correspondence, pull requests merged in 2025-03, with the labels that each got.

#772 Move purgeCorrespondence to helper
  src/Altinn.Correspondence.Application/PurgeCorrespondence/LegacyPurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHandler.cs
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
Labels: kind/bug

#777 update swagger
  src/Altinn.Correspondence.API/Models/CustomNotificationRecipientExt.cs
  src/Altinn.Correspondence.API/Models/InitializeCorrespondenceNotificationExt.cs
Labels: kind/documentation

#782 Skjul "bekreft" knapp AF
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/chore

#793 Set tls version to 1.2
  .azure/modules/storageAccount/create.bicep
Labels: kind/chore

#784 Verify creation of dialogporten dialog before publishing correspondence
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/PublishCorrespondence/PublishCorrespondenceHandler.cs
Labels: kind/user-story

#806 Fixed download of attachment
  src/Altinn.Correspondence.API/Auth/DependencyInjection.cs
  src/Altinn.Correspondence.Common/Caching/IHybridCacheWrapper.cs
  version.txt
Labels: kind/bug

#797 Fix scope in xmldoc
  src/Altinn.Correspondence.API/Controllers/AttachmentController.cs
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
Labels: kind/documentation

#780 block external access
  .azure/applications/api/main.bicep
  .azure/applications/api/params.bicepparam
  .azure/applications/migration/main.bicep
  .azure/applications/migration/params.bicepparam
  .azure/modules/containerApp/fetchEventGridIps.bicep
  .azure/modules/containerApp/main.bicep
  src/Altinn.Correspondence.API/Program.cs
  src/Altinn.Correspondence.API/appsettings.Development.json
  src/Altinn.Correspondence.Application/IpSecurityRestrictionsUpdater.cs/IpSecurityRestrictionsUpdater.cs
  src/Altinn.Correspondence.Core/Altinn.Correspondence.Core.csproj
  src/Altinn.Correspondence.Core/Services/IResourceManager.cs
  src/Altinn.Correspondence.Integrations/Altinn.Correspondence.Integrations.csproj
  src/Altinn.Correspondence.Integrations/Azure/AzureResourceManagerOptions.cs
  src/Altinn.Correspondence.Integrations/Azure/AzureResourceManagerService.cs
  src/Altinn.Correspondence.Integrations/DependencyInjection.cs
Labels: kind/feature

#808 Re-enabled adaptive sampling
  src/Altinn.Correspondence.API/Program.cs
Labels: kind/feature

#811 Retrieve APIM IP from Github environment secrets
  .azure/applications/api/params.bicepparam
  .github/actions/deploy-to-environment/action.yml
  .github/actions/release-version/action.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/deploy-to-environment.yml
  .github/workflows/publish-branch.yml
Labels: kind/enhancement

#805 Set opened activity for dialogporten on content endpoint call
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceOverview/GetCorrespondenceOverviewHandler.cs
  src/Altinn.Correspondence.Core/Services/IDialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogActivityRequestMapper.cs
Labels: kind/enhancement

#817 Allow altinntoken authentication for content endpoint
  src/Altinn.Correspondence.API/Controllers/CorrespondenceController.cs
Labels: kind/enhancement

#839 Fix showing of correct party in LegacyHistory
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/Base/LegacyTestBase.cs
  Test/Altinn.Correspondence.Tests/TestingController/Legacy/LegacyRetrievalTests.cs
  src/Altinn.Correspondence.Application/GetCorrespondenceHistory/LegacyGetCorrespondenceHistoryHandler.cs
  src/Altinn.Correspondence.Application/Helpers/CorrespondenceExtensions.cs
  src/Altinn.Correspondence.Core/Services/IAltinnRegisterService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterDevService.cs
  src/Altinn.Correspondence.Integrations/Altinn/Register/AltinnRegisterService.cs
Labels: kind/bug, product/meldingstjenesten

#826 Remove archive as a GUI action in dialogporten
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
  src/Altinn.Correspondence.Core/Services/Enums/DialogportenTextType.cs
  src/Altinn.Correspondence.Core/Services/Mappers/DialogportenText.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/DialogportenText.cs
Labels: kind/enhancement

#840 Bugfix/migrations
  .azure/applications/migration/params.bicepparam
  .azure/modules/postgreSql/create.bicep
  .github/actions/deploy-to-environment/action.yml
  .github/actions/migrate-database/action.yml
Labels: kind/bug

#813 Changed scheduling of publish to handle delayed virus scan better
  Test/Altinn.Correspondence.Tests/Helpers/CorrespondenceHelper.cs
  Test/Altinn.Correspondence.Tests/Helpers/CustomWebApplicationFactory.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceAttachmentTests.cs
  Test/Altinn.Correspondence.Tests/TestingController/Correspondence/CorrespondenceInitializationTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/MalwareScanResultControllerTests.cs
  src/Altinn.Correspondence.API/Auth/CascadeAuthenticationHandler.cs
  src/Altinn.Correspondence.Application/DependencyInjection.cs
  src/Altinn.Correspondence.Application/Helpers/HangfireScheduleHelper.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
  src/Altinn.Correspondence.Common/Caching/HybridCacheWrapper.cs
  src/Altinn.Correspondence.Common/Caching/IHybridCacheWrapper.cs
  src/Altinn.Correspondence.Core/Repositories/ICorrespondenceRepostitory.cs
  src/Altinn.Correspondence.Persistence/Repositories/CorrespondenceRepository.cs
Labels: kind/bug

#838 Added dialogporten correspondence scope to maskinportenSettings scopes
  .azure/modules/containerApp/main.bicep
  src/Altinn.Correspondence.API/appsettings.Development.json
Labels: kind/bug

#847 missing space
  src/Altinn.Correspondence.API/Models/CorrespondenceReplyOptionExt.cs
Labels: kind/bug

#846 Added a withoutPrefix call so that the ssn validation ignore the prefix
  Test/Altinn.Correspondence.Tests/TestingUtility/StringExtensionsTests.cs
  src/Altinn.Correspondence.Application/Helpers/InitializeCorrespondenceHelper.cs
  src/Altinn.Correspondence.Common/Helpers/StringExtensions.cs
  src/Altinn.Correspondence.Integrations/Altinn/ContactReservationRegistry/ContactReservationRegistryService.cs
Labels: kind/bug

#849 Fix information activity after purge
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
Labels: kind/bug

#852 Pass only ID as job parameter, not entire entity
  src/Altinn.Correspondence.Application/Helpers/HangfireScheduleHelper.cs
  src/Altinn.Correspondence.Application/InitializeCorrespondences/InitializeCorrespondencesHandler.cs
  src/Altinn.Correspondence.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/chore

#850 Increase Redis performance in prod
  .azure/infrastructure/main.bicep
  .azure/modules/redis/main.bicep
Labels: kind/chore

#853 set async
  src/Altinn.Correspondence.Application/PurgeCorrespondence/PurgeCorrespondenceHelper.cs
Labels: kind/bug

#854 Remove "Mark as Read" from Dialogporten
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/feature

#858 bump version
  version.txt
Labels: kind/documentation, ignore-for-release

#861 Update based on malwarescan transactionally
  src/Altinn.Correspondence.Application/EnsureNotification/EnsureNotificationHandler.cs
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
Labels: kind/chore

#865 Enhancement/deactivate dialog confirm button
  Test/Altinn.Correspondence.Tests/Factories/CorrespondenceEntityBuilder.cs
  Test/Altinn.Correspondence.Tests/TestingFeature/DialogportenTests.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHandler.cs
  src/Altinn.Correspondence.Application/UpdateCorrespondenceStatus/UpdateCorrespondenceStatusHelper.cs
  src/Altinn.Correspondence.Core/Services/IDialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenDevService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/DialogportenService.cs
  src/Altinn.Correspondence.Integrations/Dialogporten/Factories/PatchDialogRequestBuilder.cs
Labels: kind/enhancement

#870 Use appropriate isolation level for transaction
  src/Altinn.Correspondence.Application/MalwareScanResult/MalwareScanResultHandler.cs
Labels: kind/bug

#877 862 - removed mark as read and update confirm
  src/Altinn.Correspondence.Integrations/Dialogporten/Mappers/CreateDialogRequestMapper.cs
Labels: kind/enhancement
